name: Build

on: 
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@main

      - name: Installing AngleSharp
        run: |
          # https://github.com/AngleSharp/AngleSharp
          Install-Package AngleSharp -Source https://www.nuget.org/api/v2 -SkipDependencies -Force

      - name: YouTube
        run: |
          New-Item -Path Temp -ItemType Directory -Force

          . Scripts\YouTube.ps1

      - name: ReVanced CLI
        run: |
          . Scripts\ReVanced_CLI.ps1

      - name: Downloading ReVanced Patches
        run: |
          . Scripts\ReVanced_Patches.ps1

      - name: ReVanced Integrations
        run: |
          . Scripts\ReVanced_Intergrations.ps1

      - name: Vanced MicroG
        run: |
          . Scripts\MicroG.ps1

      - name: Zulu JDK
        run: |
          . Scripts\Zulu_JDK.ps1

      - name: Building
        run: |
          # https://github.com/revanced/revanced-patches
          & "$env:ProgramFiles\Zulu\zulu*\bin\java.exe" `
          -jar "Temp\revanced-cli.jar" `
          --apk "Temp\youtube.apk" `
          --bundle "Temp\revanced-patches.jar" `
          --merge "Temp\revanced-integrations.apk" `
          --include comments --include premium-heading --include hide-captions-button --include disable-fullscreen-panels --include copy-video-url  --include custom-video-buffer  --include disable-auto-captions --include disable-player-popup-panels --include downloads --include general-ads --include hdr-auto-brightness --include hide-crowdfunding-box --include hide-floating-microphone-button --include hide-watch-in-vr --include minimized-playback --include hide-watermark --include open-links-externally --include return-youtube-dislike --include sponsorblock --include swipe-controls --include vanced-microg-support --include video-ads `
          --clean `
          --temp-dir "Temp\Temp" `
          --out "Temp\revanced.apk"

      - name: Creating archive
        run: |
          $Parameters = @{
              Path             = "Temp\revanced.apk", "Temp\microg.apk"
              DestinationPath  = "ReVanced.zip"
              CompressionLevel = "Fastest"
              Force            = $true
          }
          Compress-Archive @Parameters

      - name: ReleaseNotesTemplate
        id: read_release
        run: |
          # https://en.wikipedia.org/wiki/Percent-encoding
          (Get-Content -Path ReleaseNotesTemplate.md -Encoding utf8 -Raw).replace("YouTubeTag", "${{ env.LatestSupportedYT }}").replace("CLITag", "${{ env.CLIvtag }}").replace("PatchesTag", "${{ env.Patchesvtag }}").replace("IntegrationsTag", "${{ env.IntegrationsTag }}").replace("MicroGTag", "${{ env.MicroGTag }}").replace("ZuluTag", "${{ env.ZuluTag }}") | Set-Content -Path ReleaseNotesTemplate.md -Encoding utf8 -Force

          # https://trstringer.com/github-actions-multiline-strings/
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ReleaseBody=ReleaseNotesTemplate.md"

          $ReleaseName = Get-Date -f "yyyy.MM.dd"
          echo "RELEASE_NAME=$ReleaseName" >> $env:GITHUB_ENV

      - name: Uploading
        uses: softprops/action-gh-release@master
        with:
          name: ${{ env.RELEASE_NAME }}
          token: ${{ github.token }}
          files: ReVanced.zip
          body_path: ${{ steps.read_release.outputs.ReleaseBody }}
